name: Python CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [[ -f requirements.txt ]]; then pip install -r requirements.txt; fi

    - name: Lint code
      run: |
        # Install linting tools
        python -m pip install flake8

        # Perform linting check
        flake8 . --count --exit-zero --max-complexity=10 --statistics --verbose

    - name: Run tests
      run: |
        # Install testing framework
        python -m pip install pytest

        # Run tests
        pytest
